/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRutinaRouteImport } from './routes/app.rutina'
import { Route as AppReservasRouteImport } from './routes/app.reservas'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMedidasRouteImport } from './routes/app.medidas'
import { Route as AppComprobantesRouteImport } from './routes/app.comprobantes'
import { Route as AppClasesRouteImport } from './routes/app.clases'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRutinaRoute = AppRutinaRouteImport.update({
  id: '/rutina',
  path: '/rutina',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasRoute = AppReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMedidasRoute = AppMedidasRouteImport.update({
  id: '/medidas',
  path: '/medidas',
  getParentRoute: () => AppRoute,
} as any)
const AppComprobantesRoute = AppComprobantesRouteImport.update({
  id: '/comprobantes',
  path: '/comprobantes',
  getParentRoute: () => AppRoute,
} as any)
const AppClasesRoute = AppClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/clases': typeof AppClasesRoute
  '/app/comprobantes': typeof AppComprobantesRoute
  '/app/medidas': typeof AppMedidasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/rutina': typeof AppRutinaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/clases': typeof AppClasesRoute
  '/app/comprobantes': typeof AppComprobantesRoute
  '/app/medidas': typeof AppMedidasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/rutina': typeof AppRutinaRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/clases': typeof AppClasesRoute
  '/app/comprobantes': typeof AppComprobantesRoute
  '/app/medidas': typeof AppMedidasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/rutina': typeof AppRutinaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/clases'
    | '/app/comprobantes'
    | '/app/medidas'
    | '/app/perfil'
    | '/app/reservas'
    | '/app/rutina'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/clases'
    | '/app/comprobantes'
    | '/app/medidas'
    | '/app/perfil'
    | '/app/reservas'
    | '/app/rutina'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/app/clases'
    | '/app/comprobantes'
    | '/app/medidas'
    | '/app/perfil'
    | '/app/reservas'
    | '/app/rutina'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rutina': {
      id: '/app/rutina'
      path: '/rutina'
      fullPath: '/app/rutina'
      preLoaderRoute: typeof AppRutinaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservas': {
      id: '/app/reservas'
      path: '/reservas'
      fullPath: '/app/reservas'
      preLoaderRoute: typeof AppReservasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medidas': {
      id: '/app/medidas'
      path: '/medidas'
      fullPath: '/app/medidas'
      preLoaderRoute: typeof AppMedidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comprobantes': {
      id: '/app/comprobantes'
      path: '/comprobantes'
      fullPath: '/app/comprobantes'
      preLoaderRoute: typeof AppComprobantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clases': {
      id: '/app/clases'
      path: '/clases'
      fullPath: '/app/clases'
      preLoaderRoute: typeof AppClasesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClasesRoute: typeof AppClasesRoute
  AppComprobantesRoute: typeof AppComprobantesRoute
  AppMedidasRoute: typeof AppMedidasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppReservasRoute: typeof AppReservasRoute
  AppRutinaRoute: typeof AppRutinaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClasesRoute: AppClasesRoute,
  AppComprobantesRoute: AppComprobantesRoute,
  AppMedidasRoute: AppMedidasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppReservasRoute: AppReservasRoute,
  AppRutinaRoute: AppRutinaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
